replicaCount: 1

image:
  repository: kalostoykov/simple-go-service
  tag: "testing"

livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  httpGet:
    path: /v1/data
    port: 8080
    httpHeaders:
      - name: "If-Modified-Since"
        value: "MON, 23 SEP 2024 15:04:05 GMT"

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 5
  httpGet:
    path: /v1/data
    port: 8080
    httpHeaders:
      - name: "If-Modified-Since"
        value: "MON, 23 SEP 2024 15:04:05 GMT"

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

healthCheckCronjob:
  enabled: true
  image:
    repository: alpine
    tag: "3.14"
    pullPolicy: IfNotPresent
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  script: |
    #!/bin/bash

    apk add curl

    server="simple-go-service.simple-go-service.svc.cluster.local"
    port=8080
    endpoint="/v1/data"
    requestheader="If-Modified-Since: Tue, 24 Sep 2024 10:10:24 GMT"
    if [ $(curl -o /dev/null -s -w "%{http_code}\n" --header "${requestheader}" ${server}:${port}${endpoint}) != 200 ]; then
    echo "Send notification via sendmail or similar"
    fi

    exit 0